version: "3.8"

services:
  webthings-gateway:
    container_name: weconnecth
    image: ccunknown/weconnecth:0.1.0
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - "TZ=Asia/Bangkok"
    volumes:
      - ./webthings-config:/home/node/.webthings
      # - ./redis-config:/etc/redis
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
