version: "3.8"

services:
  webthings-gateway:
    container_name: weconnecth
    image: ccunknown/weconnecth:0.2.0
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - "TZ=Asia/Bangkok"
    volumes:
      - ./webthings-config:/home/node/.webthings
      #- ./lime-scripts:/home/node/extensions/lime-extension/src/service/scripts-service/scripts
      - ./default.js:/home/node/webthings/gateway/config/default.js
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
